### ISSUE TITLE
Problem with humidex_f()

### ISSUE THREAD

**Issue by 4dtdgit** [pilotak/MeteoFunctions#1]
Thank you for taking the time to create and share MeteoFunctions. 

I believe I've found one minor defect. In calls to humidex_f(), incorrect values are returned which are notably close to humidex_c() values. I believe converting the function result from celsius to fahrenheit yields the correct value as shown below. 

/**
 * Calculates humidex in Fahrenheit
 */
float MeteoFunctions::humidex_f(float temp_f, float humidity) {
    return humidex_c(f_c(temp_f), humidity);
}

/** 
 * REVISED to include addition of c_f() 
*/
float MeteoFunctions::humidex_f(float temp_f, float humidity) {
    return c_f(humidex_c(f_c(temp_f), humidity));
}

**Comment by pilotak** [comment]
You right there is a bug, thanks for spotting it. Do you want to create a pull request?

**Comment by 4dtdgit** [comment]
I don’t see any need as it’s pretty trivial. Thanks again for a great library.
